// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modemas.Server.Data;

#nullable disable

namespace Modemas.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214134622_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Modemas.Server.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "points");

                    b.Property<int?>("QuestionTopicGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "text");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "timeLimit");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTopicGroupId");

                    b.ToTable("Questions");

                    b.HasDiscriminator<string>("QuestionType").HasValue("Question");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Modemas.Server.Models.QuestionTopicGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Topic")
                        .IsUnique();

                    b.ToTable("QuestionTopicGroups");
                });

            modelBuilder.Entity("Modemas.Server.Models.MultipleAnswerQuestion", b =>
                {
                    b.HasBaseType("Modemas.Server.Models.Question");

                    b.PrimitiveCollection<string>("Choices")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "choices");

                    b.PrimitiveCollection<string>("CorrectAnswerIndices")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "correctAnswerIndices");

                    b.ToTable("Questions", t =>
                        {
                            t.Property("Choices")
                                .HasColumnName("MultipleAnswerQuestion_Choices");
                        });

                    b.HasDiscriminator().HasValue("MultipleAnswer");
                });

            modelBuilder.Entity("Modemas.Server.Models.MultipleChoiceQuestion", b =>
                {
                    b.HasBaseType("Modemas.Server.Models.Question");

                    b.PrimitiveCollection<string>("Choices")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "choices");

                    b.Property<int>("CorrectAnswerIndex")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "correctAnswer");

                    b.HasDiscriminator().HasValue("MultipleChoice");
                });

            modelBuilder.Entity("Modemas.Server.Models.TrueFalseQuestion", b =>
                {
                    b.HasBaseType("Modemas.Server.Models.Question");

                    b.Property<bool>("CorrectAnswer")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "correctAnswer");

                    b.HasDiscriminator().HasValue("TrueFalse");
                });

            modelBuilder.Entity("Modemas.Server.Models.Question", b =>
                {
                    b.HasOne("Modemas.Server.Models.QuestionTopicGroup", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTopicGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Modemas.Server.Models.QuestionTopicGroup", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
